import { keysOf } from "@project/shared/src/utils/Helper";
import { $t, L } from "../../utils/i18n";
import type { Culture } from "./Culture";
import type { ProvinceUpgrade } from "./ProvinceUpgrades";
import type { Religion } from "./Religion";

interface IProvinceConfig {
   code: string;
   name: () => string;
   culture: Culture;
   religion: Religion;
   upgrades: ProvinceUpgrade[];
}

export const Province = {
   Achaia: { code: "AC", name: () => $t(L.ProvinceAchaia), culture: "Greek", religion: "GrecoRoman", upgrades: [] },
   Aegyptus: {
      code: "AE",
      name: () => $t(L.ProvinceAegyptus),
      culture: "Egyptian",
      religion: "Egyptian",
      upgrades: [],
   },
   Africa: {
      code: "AF",
      name: () => $t(L.ProvinceAfrica),
      culture: "Punic",
      religion: "GrecoRoman",
      upgrades: ["LittoralTaxDistricts", "MercantileMobilization", "GranaryOfTheEmpire"],
   },
   Aquitania: {
      code: "AQ",
      name: () => $t(L.ProvinceAquitania),
      culture: "Gallic",
      religion: "Celtic",
      upgrades: ["SereneVineyards", "CultivatedEstates", "HillfortBastion"],
   },
   Asia: { code: "AS", name: () => $t(L.ProvinceAsia), culture: "Greek", religion: "GrecoRoman", upgrades: [] },
   Baetica: {
      code: "BA",
      name: () => $t(L.ProvinceBaetica),
      culture: "Iberian",
      religion: "Iberian",
      upgrades: ["CommandOfThePillars", "OpulentPortCities", "WorkshopOfTheWest"],
   },
   Belgica: {
      code: "BE",
      name: () => $t(L.ProvinceBelgica),
      culture: "Gallic",
      religion: "Celtic",
      upgrades: ["RangedPredominance", "BravestOfTheGauls", "MartialSociety"],
   },
   Bithynia: {
      code: "BI",
      name: () => $t(L.ProvinceBithynia),
      culture: "Greek",
      religion: "GrecoRoman",
      upgrades: [],
   },
   Britannia: {
      code: "BR",
      name: () => $t(L.ProvinceBritannia),
      culture: "Brittonic",
      religion: "Celtic",
      upgrades: ["MaritimeAmbition", "NavalTradition", "CoastalMandate"],
   },
   Cappadocia: {
      code: "CA",
      name: () => $t(L.ProvinceCappadocia),
      culture: "Cappadocian",
      religion: "Anatolian",
      upgrades: [],
   },
   Cilicia: { code: "CI", name: () => $t(L.ProvinceCilicia), culture: "Anatolian", religion: "Eastern", upgrades: [] },
   Corsica: {
      code: "CO",
      name: () => $t(L.ProvinceCorsica),
      culture: "Corsican",
      religion: "GrecoRoman",
      upgrades: [],
   },
   Cyrenaica: {
      code: "CY",
      name: () => $t(L.ProvinceCyrenaica),
      culture: "Greek",
      religion: "GrecoRoman",
      upgrades: [],
   },
   Dacia: { code: "DA", name: () => $t(L.ProvinceDacia), culture: "Dacian", religion: "GrecoRoman", upgrades: [] },
   Dalmatia: {
      code: "DL",
      name: () => $t(L.ProvinceDalmatia),
      culture: "Illyrian",
      religion: "GrecoRoman",
      upgrades: ["HighlandRecruitment", "MonumentsOfPower", "CapitalsOfProsperity"],
   },
   Epirus: { code: "EP", name: () => $t(L.ProvinceEpirus), culture: "Greek", religion: "GrecoRoman", upgrades: [] },
   Galatia: {
      code: "GA",
      name: () => $t(L.ProvinceGalatia),
      culture: "Anatolian",
      religion: "Anatolian",
      upgrades: [],
   },
   Germania: {
      code: "GE",
      name: () => $t(L.ProvinceGermania),
      culture: "Germanic",
      religion: "Germanic",
      upgrades: ["FortifiedAdministration", "VeteranGenerals", "UnitedFrontier"],
   },
   Italia: {
      code: "IT",
      name: () => $t(L.ProvinceItalia),
      culture: "Italic",
      religion: "GrecoRoman",
      upgrades: ["SenatorialAuthority", "InclusiveCitizenship", "CaputMundi", "ExperiencedCommand"],
   },
   Judea: { code: "JU", name: () => $t(L.ProvinceJudea), culture: "Arab", religion: "Judaism", upgrades: [] },
   Lusitania: {
      code: "LS",
      name: () => $t(L.ProvinceLusitania),
      culture: "Iberian",
      religion: "Iberian",
      upgrades: ["TreatyRevenues", "VictoriousLeadership", "PaxLusitana"],
   },
   Lycia: { code: "LY", name: () => $t(L.ProvinceLycia), culture: "Anatolian", religion: "Anatolian", upgrades: [] },
   Lugdunensis: {
      code: "LG",
      name: () => $t(L.ProvinceLugdunensis),
      culture: "Gallic",
      religion: "Celtic",
      upgrades: ["CavalryWarPower", "TradeProfitForEachTrade", "ChristianFervor"],
   },
   Macedonia: {
      code: "MC",
      name: () => $t(L.ProvinceMacedonia),
      culture: "Greek",
      religion: "GrecoRoman",
      upgrades: [],
   },
   Mauretania: {
      code: "MR",
      name: () => $t(L.ProvinceMauretania),
      culture: "Berber",
      religion: "Berber",
      upgrades: ["TheTwoShores", "MoorishMuster", "MaritimeRenown"],
   },
   Moesia: {
      code: "MO",
      name: () => $t(L.ProvinceMoesia),
      culture: "Thracian",
      religion: "GrecoRoman",
      upgrades: [],
   },
   Narbonensis: {
      code: "NB",
      name: () => $t(L.ProvinceNarbonensis),
      culture: "Gallic",
      religion: "GrecoRoman",
      upgrades: ["MunicipalPrivilege", "MaritimeProsperity", "CommercialAlliances"],
   },
   Noricum: {
      code: "NO",
      name: () => $t(L.ProvinceNoricum),
      culture: "Noric",
      religion: "GrecoRoman",
      upgrades: ["MulticulturalArmy", "InlandAmbition", "TriumphalUnity"],
   },
   Pannonia: {
      code: "PN",
      name: () => $t(L.ProvincePannonia),
      culture: "Pannonian",
      religion: "GrecoRoman",
      upgrades: ["CrossroadsTaxDistricts", "BountifulFrontiers", "WartimeAdministration"],
   },
   Raetia: {
      code: "RA",
      name: () => $t(L.ProvinceRaetia),
      culture: "Raetian",
      religion: "GrecoRoman",
      upgrades: ["MastersOfThePasses", "ProductiveInvestment", "CommercialRenown"],
   },
   Sardinia: {
      code: "SA",
      name: () => $t(L.ProvinceSardinia),
      culture: "Sardinian",
      religion: "GrecoRoman",
      upgrades: [],
   },
   Sicilia: {
      code: "SC",
      name: () => $t(L.ProvinceSicilia),
      culture: "Greek",
      religion: "GrecoRoman",
      upgrades: ["MediterraneanAmbition", "BountifulCoastlines", "CoastalAdministration"],
   },
   Syria: { code: "SY", name: () => $t(L.ProvinceSyria), culture: "Syrian", religion: "Eastern", upgrades: [] },
   Tarraconensis: {
      code: "TR",
      name: () => $t(L.ProvinceTarraconensis),
      culture: "Iberian",
      religion: "Iberian",
      upgrades: ["CulturalEfficiency", "ChristianTranquility", "FocusedGovernance"],
   },
   Thracia: {
      code: "TH",
      name: () => $t(L.ProvinceThracia),
      culture: "Thracian",
      religion: "GrecoRoman",
      upgrades: [],
   },
   Suebi: { code: "SU", name: () => $t(L.ProvinceSuebi), culture: "Germanic", religion: "Germanic", upgrades: [] },
   Visigoths: {
      code: "VI",
      name: () => $t(L.ProvinceVisigoths),
      culture: "Germanic",
      religion: "Germanic",
      upgrades: [],
   },
   Vandals: {
      code: "VA",
      name: () => $t(L.ProvinceVandals),
      culture: "Germanic",
      religion: "Germanic",
      upgrades: [],
   },
   Burgundians: {
      code: "BU",
      name: () => $t(L.ProvinceBurgundians),
      culture: "Germanic",
      religion: "Germanic",
      upgrades: [],
   },
   Franks: { code: "FR", name: () => $t(L.ProvinceFranks), culture: "Germanic", religion: "Germanic", upgrades: [] },
   Saxons: { code: "SX", name: () => $t(L.ProvinceSaxons), culture: "Germanic", religion: "Germanic", upgrades: [] },
   Alemanni: {
      code: "AL",
      name: () => $t(L.ProvinceAlemanni),
      culture: "Germanic",
      religion: "Germanic",
      upgrades: [],
   },
   Ostrogoths: {
      code: "OS",
      name: () => $t(L.ProvinceOstrogoths),
      culture: "Germanic",
      religion: "Germanic",
      upgrades: [],
   },
   Huns: { code: "HU", name: () => $t(L.ProvinceHuns), culture: "Hunnic", religion: "Hunnic", upgrades: [] },
   Avars: { code: "AV", name: () => $t(L.ProvinceAvars), culture: "Steppe", religion: "Steppe", upgrades: [] },
   Lombards: {
      code: "LO",
      name: () => $t(L.ProvinceLombards),
      culture: "Germanic",
      religion: "Arianism",
      upgrades: [],
   },
   Caliphate: { code: "CL", name: () => $t(L.ProvinceCaliphate), culture: "Arab", religion: "Islam", upgrades: [] },
   Bulgars: { code: "BG", name: () => $t(L.ProvinceBulgars), culture: "Steppe", religion: "Steppe", upgrades: [] },
} as const satisfies Record<string, IProvinceConfig>;

export type Province = keyof typeof Province;
export const Provinces = keysOf(Province);
export const EnabledProvinces: Province[] = [
   "Lugdunensis",
   "Aquitania",
   "Narbonensis",
   "Belgica",
   "Germania",
   "Tarraconensis",
   "Lusitania",
   "Baetica",
   "Italia",
   "Sicilia",
   "Mauretania",
   "Africa",
   "Britannia",
   "Raetia",
   "Noricum",
   "Pannonia",
   "Dalmatia",
];
EnabledProvinces.sort();
export const AlwaysFreeProvinces = new Set<Province>(["Lugdunensis"]);
